import pathlib
from typing import Literal, overload

import msgspec

@overload
def resolve_docker_secret(secret_name: str, *, content: Literal[False]) -> pathlib.Path: ...
@overload
def resolve_docker_secret(secret_name: str, *, content: Literal[True] = ...) -> str: ...
def resolve_docker_secret(secret_name: str, *, content: bool = True) -> pathlib.Path | str: ...
def resolve_docker_config(*, config_name: str | None = None, env_var_name: str | None = None) -> pathlib.Path: ...
@overload
def load_config_type[ConfigT: msgspec.Struct](
    path: pathlib.Path, type_: type[ConfigT], *, required: Literal[False]
) -> ConfigT | None: ...
@overload
def load_config_type[ConfigT: msgspec.Struct](
    path: pathlib.Path, type_: type[ConfigT], *, required: Literal[True] = ...
) -> ConfigT: ...
def load_config_type[ConfigT: msgspec.Struct](
    path: pathlib.Path, type_: type[ConfigT], *, required: bool = True
) -> ConfigT | None: ...
